baseURL = '/'
defaultContentLanguage = "en"
languageCode = "en"
title = "CoreDump"
theme = "typo"

[params]
description = "Sort of a braindump"
theme = 'auto'
colorPalette = 'default'
hideHeader = true

homeIntroContent = "Where some of my thoughts live"

homeCollectionTitle = 'Posts'
homeCollection = 'posts'
paginationSize = 50
listSummaries = false
listDateFormat = '2 Jan, 2006'

breadcrumbs = true
math = true

[[params.social]]
name = "github"
url = "https://github.com/musaubrian"

[[params.social]]
name = "bluesky"
url = "https://ulong.bsky.social"

[[params.social]]
name = "rss"
url = "/index.xml"


# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "projects"
url = "/projects"


# [[params.menu]]
# name = "cv"
# url = "https://cv.nabri.xyz"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'
