baseURL = '/'
defaultContentLanguage = "en"
languageCode = "en"
title = "CoreDump"
theme = "typo"

[params]
description = "Sort of a braindump"
theme = 'auto'
colorPalette = 'default'
hideHeader = true

homeIntroContent = "Building stuff then trying to remember to write about them"

homeCollectionTitle = 'Posts'
homeCollection = 'posts'
paginationSize = 5
listSummaries = false
listDateFormat = '2 Jan, 2006'

breadcrumbs = true

[[params.social]]
name = "github"
url = "https://github.com/musaubrian"

[[params.social]]
name = "twitter"
url = "https://x.com/0xMusau"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/ernest-musau/"


# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "projects"
url = "/projects"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'
